import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = Readonly<{
    children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props): React.JSX.Element {
    return (
        <html lang="en">
            <body className={font.className}>{children}</body>
        </html>
    );
}
